server:
  port: 8091

spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/yuan
   username: root
   password: root

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/templates/

  # thymeleaf configeration start
#spring:
  tymeleaf:
    model: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    cache: false

#pdf path in server
pdf:
  path: /home/zule/yuan/pdf

project:
  index:
    url: http://www.sexygirls.net.cn
# thymeleaf configeration end